"""Platform adapters.

Each adapter answers two questions: can I dispatch a training session right
now, and did the last one finish? Everything else -- who holds the run, where
the checkpoint is, what step we are on -- is the relay's job, not the adapter's.

That split is what keeps the orchestrator crash-safe. An adapter never has to
track a job to completion, because the lease already does: if a dispatched
session dies, its lease expires and the next tick redispatches.

Automation status per platform:

  kaggle-gpu / kaggle-tpu   official API (`kernels push`), fully automatable
  colab                     official CLI (`colab run`), headless; free-tier
                            support is UNVERIFIED -- test before relying on it
  lightning                 SDK; adapter is a stub
  studiolab                 no API at all; manual only
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..config import ProjectConfig


@dataclass
class DispatchResult:
    ok: bool
    platform: str
    ref: str = ""
    detail: str = ""
    retryable: bool = True


class Adapter:
    name = "base"
    automatable = False

    def __init__(self, cfg: ProjectConfig) -> None:
        self.cfg = cfg

    def preflight(self) -> tuple[bool, str]:
        """Can this adapter dispatch right now?"""
        return False, "not implemented"

    def dispatch(self, config_path: str, worker_id: str) -> DispatchResult:
        raise NotImplementedError

    def status(self, ref: str) -> str:
        """running | complete | error | unknown"""
        return "unknown"


# ------------------------------------------------------------------ #
# Kaggle
# ------------------------------------------------------------------ #


KAGGLE_NOTEBOOK = '''\
# Bussin worker -- generated by the orchestrator. Do not edit in the UI.
#
# The source arrives as a mounted Kaggle Dataset rather than a git clone:
# attached inputs are mounted, not downloaded, so they cost no session time.
import os, subprocess, sys, time
T0 = time.time()
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Prefer Kaggle Secrets so the token never sits in kernel source. Add it under
# Add-ons -> Secrets as HF_TOKEN. The embedded value is a fallback for the
# private kernel the orchestrator pushes.
try:
    from kaggle_secrets import UserSecretsClient
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
    print("HF token from Kaggle secrets", flush=True)
except Exception:
    os.environ["HF_TOKEN"] = "{hf_token}"
    print("HF token from kernel source (add a Kaggle secret to avoid this)", flush=True)

# Find the mounted source rather than assuming a path. Kaggle derives the
# mount folder from the dataset slug, but not always the way you expect, and a
# wrong guess wastes a whole dispatch.
INPUT = "/kaggle/input"
print("mounted inputs:", os.listdir(INPUT) if os.path.isdir(INPUT) else "<none>",
      flush=True)

CODE = None
for base, dirs, files in os.walk(INPUT):
    if os.path.basename(base) == "relay" and "bootstrap.py" in files:
        CODE = os.path.dirname(os.path.dirname(base))   # .../<root>/bussin/relay
        break
    if base.count(os.sep) > INPUT.count(os.sep) + 4:
        dirs[:] = []                                     # keep the walk shallow
if CODE is None:
    raise SystemExit(
        f"bussin source not found under {{INPUT}}; attach {code_slug}. "
        f"Present: {{os.listdir(INPUT) if os.path.isdir(INPUT) else []}}"
    )
print("source:", CODE, flush=True)
sys.path.insert(0, CODE)
os.chdir(CODE)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "hf_transfer", "safetensors", "huggingface_hub", "pyyaml", "regex"],
               check=False)
print(f"setup {{time.time() - T0:.1f}}s", flush=True)

CONFIG = "{config}"
if not os.path.isabs(CONFIG):
    CONFIG = os.path.join(CODE, CONFIG)
if not os.path.exists(CONFIG):
    raise SystemExit(f"config not found: {{CONFIG}}")

from bussin.relay.bootstrap import run
sys.exit(run(CONFIG, local_root=None))
'''

KAGGLE_METADATA = {
    "id": "",
    "title": "",
    "code_file": "worker.py",
    "language": "python",
    "kernel_type": "script",
    "is_private": True,
    "enable_gpu": False,
    "enable_tpu": False,
    "enable_internet": True,
    "dataset_sources": [],
    "competition_sources": [],
    "kernel_sources": [],
    "model_sources": [],
}


class KaggleAdapter(Adapter):
    name = "kaggle"
    automatable = True

    def __init__(self, cfg: ProjectConfig, accelerator: str = "gpu",
                 code_slug: str = "", datasets: list[str] | None = None) -> None:
        super().__init__(cfg)
        self.accelerator = accelerator          # gpu | tpu
        self.name = f"kaggle-{accelerator}"
        self.code_slug = code_slug or os.environ.get(
            "BUSSIN_CODE_DATASET",
            f"{cfg.creds.kaggle_username}/bussin-code" if cfg.creds.kaggle_username else "",
        )
        self.datasets = datasets or []
        self._api = None

    @property
    def code_dir(self) -> str:
        return f"/kaggle/input/{self.code_slug.split('/')[-1]}"

    # -------------------------------------------------------------- #

    def api(self):
        if self._api is None:
            self.cfg.creds.export_kaggle()
            self.cfg.creds.write_kaggle_json()
            from kaggle.api.kaggle_api_extended import KaggleApi

            api = KaggleApi()
            api.authenticate()
            self._api = api
        return self._api

    def preflight(self) -> tuple[bool, str]:
        if not (self.cfg.creds.kaggle_username and self.cfg.creds.kaggle_key):
            return False, "KAGGLE_USERNAME / KAGGLE_KEY not set"
        try:
            self.api().kernels_list(mine=True, page_size=1)
        except Exception as exc:
            msg = str(exc)
            if "401" in msg or "Unauthorized" in msg:
                # KGAT_ access tokens expire after ~3 hours. Unattended running
                # needs a legacy API key (kaggle.com/settings/api -> Legacy API
                # Credentials), which does not expire.
                return False, (
                    "Kaggle credentials rejected (401). A KGAT_ access token "
                    "expires after ~3h; use a Legacy API key for unattended runs."
                )
            return False, f"{type(exc).__name__}: {msg[:160]}"
        if not self.code_slug:
            return False, "no code dataset (run scripts/push_code_dataset.py)"
        try:
            self.api().dataset_status(self.code_slug)
        except Exception:
            return False, (f"code dataset {self.code_slug} not found -- "
                           f"run scripts/push_code_dataset.py")
        return True, "ok"

    def _slug(self, worker_id: str) -> str:
        return f"{self.cfg.creds.kaggle_username}/bussin-{self.accelerator}-worker"

    def dispatch(self, config_path: str, worker_id: str) -> DispatchResult:
        ok, why = self.preflight()
        if not ok:
            return DispatchResult(False, self.name, detail=why, retryable=False)

        slug = self._slug(worker_id)
        work = Path(tempfile.mkdtemp(prefix="bussin_kernel_"))
        try:
            (work / "worker.py").write_text(
                KAGGLE_NOTEBOOK.format(
                    hf_token=self.cfg.creds.hf_token or "",
                    code_dir=self.code_dir,
                    code_slug=self.code_slug,
                    config=config_path,
                ),
                encoding="utf-8",
            )
            meta = dict(KAGGLE_METADATA)
            meta.update(
                id=slug,
                title=f"bussin {self.accelerator} worker",
                enable_gpu=self.accelerator == "gpu",
                enable_tpu=self.accelerator == "tpu",
                dataset_sources=[self.code_slug] + list(self.datasets),
            )
            (work / "kernel-metadata.json").write_text(
                json.dumps(meta, indent=2), encoding="utf-8"
            )
            self.api().kernels_push(str(work))
            return DispatchResult(True, self.name, ref=slug,
                                  detail=f"pushed {slug}")
        except Exception as exc:
            return DispatchResult(False, self.name,
                                  detail=f"{type(exc).__name__}: {str(exc)[:200]}")
        finally:
            shutil.rmtree(work, ignore_errors=True)

    def status(self, ref: str) -> str:
        try:
            s = self.api().kernels_status(ref)
            raw = (getattr(s, "status", None) or
                   (s.get("status") if isinstance(s, dict) else "") or "")
            raw = str(raw).lower()
        except Exception:
            return "unknown"
        if "running" in raw or "queued" in raw:
            return "running"
        if "complete" in raw:
            return "complete"
        if "error" in raw or "cancel" in raw:
            return "error"
        return "unknown"


# ------------------------------------------------------------------ #
# Colab
# ------------------------------------------------------------------ #


class ColabAdapter(Adapter):
    """Drives the official Colab CLI.

    `colab run` executes a script on a fresh VM and releases it afterwards,
    which is exactly the shape the orchestrator wants. Two caveats:

    * The CLI is Linux/macOS only, so this works on a CI runner but not from a
      Windows workstation.
    * Whether `colab run` is available on the *free* tier is not documented.
      `preflight` reports what it finds rather than assuming.
    """

    name = "colab"
    automatable = True

    def preflight(self) -> tuple[bool, str]:
        exe = shutil.which("colab")
        if not exe:
            return False, "colab CLI not installed (`pip install google-colab-cli`)"
        try:
            p = subprocess.run(["colab", "sessions"], capture_output=True,
                               text=True, timeout=60)
        except Exception as exc:
            return False, f"colab CLI failed: {type(exc).__name__}"
        if p.returncode != 0:
            return False, f"colab CLI not authenticated: {p.stderr.strip()[:160]}"
        return True, "ok"

    def dispatch(self, config_path: str, worker_id: str) -> DispatchResult:
        ok, why = self.preflight()
        if not ok:
            return DispatchResult(False, self.name, detail=why, retryable=False)
        script = Path(tempfile.mkdtemp(prefix="bussin_colab_")) / "worker.py"
        script.write_text(
            KAGGLE_NOTEBOOK.format(
                hf_token=self.cfg.creds.hf_token or "",
                repo_url=self.repo_url if hasattr(self, "repo_url") else
                os.environ.get("BUSSIN_REPO_URL", ""),
                config=config_path,
            ).replace("/kaggle/working", "/content"),
            encoding="utf-8",
        )
        try:
            p = subprocess.Popen(
                ["colab", "run", "--gpu", "T4", "-f", str(script)],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            return DispatchResult(True, self.name, ref=str(p.pid),
                                  detail="colab run launched")
        except Exception as exc:
            return DispatchResult(False, self.name,
                                  detail=f"{type(exc).__name__}: {str(exc)[:200]}")


class LightningAdapter(Adapter):
    name = "lightning"
    automatable = True

    def preflight(self) -> tuple[bool, str]:
        if not os.environ.get("LIGHTNING_API_KEY"):
            return False, "LIGHTNING_API_KEY not set"
        if not shutil.which("lightning"):
            return False, "lightning CLI not installed"
        return True, "ok"

    def dispatch(self, config_path: str, worker_id: str) -> DispatchResult:
        return DispatchResult(False, self.name, detail="adapter not implemented",
                              retryable=False)


class ManualAdapter(Adapter):
    """Platforms with no API. The orchestrator surfaces them, never drives them."""

    automatable = False

    def __init__(self, cfg: ProjectConfig, name: str) -> None:
        super().__init__(cfg)
        self.name = name

    def preflight(self) -> tuple[bool, str]:
        return False, f"{self.name} has no API; run it by hand"


def build_adapters(cfg: ProjectConfig, code_slug: str = "",
                   datasets: list[str] | None = None) -> dict[str, Adapter]:
    return {
        "kaggle-tpu": KaggleAdapter(cfg, "tpu", code_slug, datasets),
        "kaggle-gpu": KaggleAdapter(cfg, "gpu", code_slug, datasets),
        "colab": ColabAdapter(cfg),
        "lightning": LightningAdapter(cfg),
        "studiolab": ManualAdapter(cfg, "studiolab"),
    }
