"""Run a data pipeline on a Kaggle CPU session.

CPU sessions do not consume the GPU quota, and Kaggle allows 5 concurrent batch
sessions of 12 hours each. That is roughly 60 free CPU-hours per wave, which is
where all the mining, cleaning, ranking and tokenization belongs -- a GPU
session should only ever do matrix multiplies.

The kernel mounts the code dataset, runs the pipeline, and writes results both
to /kaggle/working (so they appear as notebook output) and to a Hugging Face
dataset repo (so the next stage can fetch them without a manual download).

Run:
  python scripts/dispatch_etl.py --stage rank
  python scripts/dispatch_etl.py --stage mine --shard 0 --n-shards 5
  python scripts/dispatch_etl.py --stage rank --status
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bussin.config import project

TEMPLATE = '''\
# Bussin ETL worker -- generated by scripts/dispatch_etl.py
import os, subprocess, sys, time
T0 = time.time()
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["PYTHONUTF8"] = "1"
try:
    from kaggle_secrets import UserSecretsClient
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
except Exception:
    os.environ["HF_TOKEN"] = "{hf_token}"

INPUT = "/kaggle/input"
print("mounted:", os.listdir(INPUT) if os.path.isdir(INPUT) else "<none>", flush=True)
CODE = None
for base, dirs, files in os.walk(INPUT):
    if os.path.basename(base) == "relay" and "bootstrap.py" in files:
        CODE = os.path.dirname(os.path.dirname(base)); break
    if base.count(os.sep) > INPUT.count(os.sep) + 4:
        dirs[:] = []
if CODE is None:
    raise SystemExit("bussin source not mounted -- attach {code_slug}")
print("source:", CODE, flush=True)

# The mounted dataset is read-only; run from a writable directory.
WORK = "/kaggle/working"
os.chdir(WORK)
sys.path.insert(0, CODE)

subprocess.run([sys.executable, "-m", "pip", "install", "-q",
                "wordfreq", "xxhash", "regex", "hf_transfer", "datasets", "py3langid"],
               check=False)
print(f"setup {{time.time() - T0:.1f}}s", flush=True)

# Inputs live in the read-only mounted dataset, outputs in the writable
# working dir. "{{CODE}}" marks an argument that must resolve against the mount.
argv = [a.replace("{{CODE}}", CODE) for a in {argv!r}]
cmd = [sys.executable, os.path.join(CODE, {script!r})] + argv
print("running:", " ".join(cmd), flush=True)
rc = subprocess.run(cmd, cwd=WORK).returncode
print(f"pipeline exited {{rc}} after {{time.time() - T0:.0f}}s", flush=True)

# Publish results so the next stage does not need a manual download.
if rc == 0:
    from huggingface_hub import HfApi
    api = HfApi(token=os.environ["HF_TOKEN"])
    for sub in {publish!r}:
        p = os.path.join(WORK, sub)
        if not os.path.exists(p):
            print("  nothing at", p, flush=True); continue
        api.upload_folder(repo_id={repo!r}, repo_type="dataset",
                          folder_path=p, path_in_repo=sub,
                          commit_message="etl: {stage}")
        print("  published", sub, flush=True)
sys.exit(rc)
'''

STAGES = {
    "rank": {
        "script": "pipelines/01_discover_emerging.py",
        "argv": ["--lexicon", "{CODE}/data/lexicon/lexicon.jsonl",
                 "--out", "data/lexicon/lexicon.jsonl",
                 "--emerging-out", "data/lexicon/emerging.jsonl",
                 "--communities-out", "data/lexicon/communities.json",
                 "--rank-rows", "500000", "--recent-rows", "0",
                 "--baseline-rows", "300000", "--top-communities", "400"],
        "publish": ["data/lexicon"],
        "needs_lexicon": True,
    },
    # Bounded insurance run. The full `rank` stage streams every row of three
    # Bittensor repos and only writes output at the end, so a 12h session
    # timeout loses everything. This one is sized to finish in ~1-2h and
    # produces a usable communities.json on its own.
    "rank-fast": {
        "script": "pipelines/01_discover_emerging.py",
        "argv": ["--lexicon", "{CODE}/data/lexicon/lexicon.jsonl",
                 "--out", "data/lexicon/lexicon.jsonl",
                 "--emerging-out", "data/lexicon/emerging.jsonl",
                 "--communities-out", "data/lexicon/communities.json",
                 "--rank-rows", "400000", "--recent-rows", "600000",
                 "--baseline-rows", "150000", "--top-communities", "400"],
        "publish": ["data/lexicon"],
        "needs_lexicon": True,
    },
    "mine": {
        "script": "pipelines/02_mine_corpus.py",
        "argv": ["--out", "data/corpus", "--target-tokens", "2000000000",
                 "--lexicon", "{CODE}/data/lexicon/lexicon.jsonl",
                 # Must resolve against the mount: the default is relative to
                 # the working dir, where it does not exist, and a missing file
                 # silently disables the filter instead of failing.
                 "--communities", "{CODE}/data/lexicon/communities.json",
                 # Kaggle kills a batch session at 12h. Stop at 10h so the
                 # corpus still gets published instead of dying with rc!=0.
                 "--deadline-seconds", "36000"],
        "publish": ["data/corpus"],
        "needs_lexicon": True,
    },
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", required=True, choices=sorted(STAGES))
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--n-shards", type=int, default=1)
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--log", action="store_true", help="print the kernel log")
    ap.add_argument("--extra", nargs="*", default=[])
    args = ap.parse_args()

    cfg = project()
    cfg.creds.export_kaggle()
    cfg.creds.write_kaggle_json()
    from kaggle.api.kaggle_api_extended import KaggleApi

    api = KaggleApi()
    api.authenticate()

    user = cfg.creds.kaggle_username
    slug = f"{user}/bussin-etl-{args.stage}"
    if args.n_shards > 1:
        slug += f"-{args.shard}"

    if args.status or args.log:
        try:
            st = api.kernels_status(slug)
            print(f"{slug}: {getattr(st, 'status', st)}")
        except Exception as exc:
            print(f"{slug}: {type(exc).__name__}: {str(exc)[:120]}")
            return 1
        if args.log:
            # Without a pattern this pulls every output file -- for a mine
            # shard that is gigabytes of corpus to read one log line.
            d = tempfile.mkdtemp()
            api.kernels_output(slug, path=d, file_pattern=r".*\.log$")
            for p in Path(d).rglob("*.log"):
                text = p.read_text(encoding="utf-8", errors="replace")
                try:
                    rows = json.loads(text)
                    for e in (rows if isinstance(rows, list) else [rows]):
                        s = str(e.get("data") or e.get("text") or e).rstrip()
                        if s:
                            print(s[:400])
                except json.JSONDecodeError:
                    print(text[-6000:])
        return 0

    spec = STAGES[args.stage]
    argv = list(spec["argv"]) + list(args.extra)
    if args.n_shards > 1:
        argv += ["--shard-index", str(args.shard), "--n-shards", str(args.n_shards)]

    code_slug = f"{user}/bussin-code"
    datasets = [code_slug]
    if spec.get("needs_lexicon"):
        # The lexicon is small; ship it with the code dataset rather than a
        # separate input, so there is one thing to keep in sync.
        pass

    work = Path(tempfile.mkdtemp(prefix="bussin_etl_"))
    try:
        (work / "worker.py").write_text(
            TEMPLATE.format(
                hf_token=cfg.creds.hf_token or "",
                code_slug=code_slug,
                script=spec["script"],
                argv=argv,
                publish=spec["publish"],
                repo=cfg.corpus_repo,
                stage=args.stage,
            ),
            encoding="utf-8",
        )
        (work / "kernel-metadata.json").write_text(
            json.dumps({
                "id": slug,
                "title": f"bussin etl {args.stage}"
                         + (f" {args.shard}" if args.n_shards > 1 else ""),
                "code_file": "worker.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": False,       # CPU only: costs no GPU quota
                "enable_tpu": False,
                "enable_internet": True,
                "dataset_sources": datasets,
                "competition_sources": [],
                "kernel_sources": [],
                "model_sources": [],
            }, indent=2),
            encoding="utf-8",
        )
        api.kernels_push(str(work))
        print(f"dispatched {slug}  (CPU only -- no GPU quota consumed)")
        print(f"  script : {spec['script']}")
        print(f"  args   : {' '.join(argv)}")
        print(f"  publish: {spec['publish']} -> {cfg.corpus_repo}")
        print(f"\n  watch: python scripts/dispatch_etl.py --stage {args.stage} --log")
        return 0
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
